name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

        # - name: Install Playwright Browsers
        # run: npx playwright install --with-deps
        #- name: Generate key
        #run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: 'Build Docker Resources'
      run : |
        echo --- Building and Starting up docker ---
        docker compose pull
        docker compose up -d --no-build
        sleep 30
        echo --- Containers Up ---

    - name: Check Containers
      run: docker ps

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: docker exec symbiota-laravel-web-1 php artisan test
        #- name: Run Playwright tests
        #run: npx playwright test
