name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: 'Build Docker Resources'
      run : |
        echo --- Building and Starting up docker ---
        docker compose pull
        docker compose up -d --no-build
        echo --- Containers Up ---

    - name: Debugging Container Failure
      if: failure()
      run: |
        docker ps
        docker logs symbiota-laravel-mariadb-1

    - name: Generate Application Key
      run: docker exec symbiota-laravel-web-1 php artisan key:generate

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: docker exec symbiota-laravel-web-1 php artisan test

    - name: Install Playwright Browsers
      run: docker exec symbiota-laravel-web-1 npx playwright install

    - name: Run Playwright Tests
      run: docker exec symbiota-laravel-web-1 npx playwright test
