name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

        # - name: Install Playwright Browsers
        # run: npx playwright install --with-deps
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: 'Build Docker Resources'
      run : |
        echo --- Building and Starting up docker ---
        WWWUSER="1000" WWWGROUP="1000" DB_CONNECTION="mariadb" DB_HOST="mariadb" DB_PORT="3306" DB_DATABASE="symbdb" DB_USERNAME="root" DB_PASSWORD="buildpassword" FORWARD_DB_PORT=3306 docker compose up -d
        sleep 15
        echo --- Containers Up ---

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test

        #- name: Run Playwright tests
        #run: npx playwright test
